### ISSUE TITLE
Event link.

### ISSUE THREAD

**Issue by abuhenasobuj** [sasalatart/on-this-day-scraper#1]
Can we retrieve event link? Then we can use the link as **Read more...** to go **Wikipedia**.

**Comment by sasalatart** [comment]
The page from which the scraper gets its data does not have a direct link towards each event. However, I can get links to the keywords for each event and scrap them as well. For example:

1797 - [French Revolutionary Wars](https://en.wikipedia.org/wiki/French_Revolutionary_Wars): An Austrian column is defeated by the French in the [Battle of Valvasone](https://en.wikipedia.org/wiki/Battle_of_Valvasone_(1797))

Thanks for the suggestion! :)

**Comment by abuhenasobuj** [comment]
Yes, It's good. We can use event link in Android app too. `In share action menu.`
